language: java
dist: trusty
jdk: oraclejdk8

addons:
  apt:
    packages:
      ant

sudo: required

services:
  - docker

before_install:
  - cd docker/dev
  - docker-compose up -d
  - docker ps -a

before_script:
  - cd ../../

script:
  - mvn test -P test-consumer
  - cd docker/dev
  - docker-compose stop
  - docker-compose rm -f
  - docker-compose up -d
  - docker ps -a
  - cd ../../

after_success:
  - mvn --file pom.xml cobertura:cobertura -P test-consumer,test-business
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false